include $(GOROOT)/src/Make.inc

TARG=gostat.googlecode.com/hg/stat
GOFILES=\
	stat.go\
	stat_discrete.go\
	stat_continuous.go\
	stat_mvcontinuous.go\
	stat_npb.go\
	stat_math.go\
	stat_util.go\

include $(GOROOT)/src/Make.pkg
